name: Build

on:
  push:
    branches:
        - '**'

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Generate system roots
      run: |
        bash './build.sh'
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: /tmp/*.xz*
    - name: Create release
      uses: softprops/action-gh-release@master
      with:
        tag_name: v0.2
        name: Linux musl sysroots
        files: /tmp/*.xz*
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        body: "* Update system roots"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
